on: 
  push:
    branches: [ master ]
  pull_request:

name: Run Tests

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      
      - name: Run Tests
        run: make test